[project]
name = "sphinx-example"
version = "0.1.0"
description = "A small sphinx example showing how Requiem can be used in conjunction with Sphinx"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "myst-parser>=4.0.1",
    "sphinx>=8.2.3",
]
