name: Deploy Versioned Documentation

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v0.1.0, v1.0.0, etc.
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for peaceiris/actions-gh-pages
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          # Extract version from tag (e.g., v0.1.0 -> v0.1.0)
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Deploying documentation for version: $VERSION"

      - name: Install mdBook
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook

      - name: Build documentation with version info
        run: |
          # Add version to book title
          VERSION=${{ steps.version.outputs.version }}
          sed -i "s/title = \"Requiem User Guide\"/title = \"Requiem User Guide ($VERSION)\"/" docs/book.toml
          mdbook build
        working-directory: docs

      - name: Deploy to GitHub Pages (versioned subdirectory)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
          # Deploy to /vX.Y.Z/ subdirectory
          destination_dir: ${{ steps.version.outputs.version }}
          # Keep existing files (don't delete other versions)
          keep_files: true
